### ISSUE TITLE
Update geneset processors and generators to remove duplicated genes

### ISSUE THREAD

**Issue by hadalin** [genialis/resolwe-bio#161]
Processors:

- `create-geneset`
- `upload-geneset`
- `create-geneset-venn`

Also add a warning if there are duplicated genes.

**Comment by hadalin** [comment]
cc @jkokosar

**Comment by mstajdohar** [comment]
And sort genes alphabetically.

**Comment by mstajdohar** [comment]
Great suggestion @hadalin.
