### ISSUE TITLE
Make EnrichmentProcessorTestCase independent from external API server

### ISSUE THREAD

**Issue by tjanez** [genialis/resolwe-bio#173]
Currently, [EnrichmentProcessorTestCase](https://github.com/genialis/resolwe-bio/blob/a7aabe1931776ff0a9e487317a8b848f857244a4/resolwe_bio/tests/processes/test_enrichment.py#L5-L40) needs to access gene knowledge base on an [external API server](https://github.com/genialis/resolwe-bio/blob/a7aabe1931776ff0a9e487317a8b848f857244a4/tests/settings.py#L14) which is prone to test's failures and inconsistencies.
Replace this by using [Resolwe's custom `LiveServerTestCase`](https://github.com/genialis/resolwe/issues/182).

Prerequisites:

- [ ] Implement [Resolwe's custom `LiveServerTestCase`](https://github.com/genialis/resolwe/issues/182).
- [x] Finish implementation of [Resolwe's elastic app](https://github.com/genialis/resolwe/pull/177).
- [x] Port Resolwe Bioinformatics gene knowledge base from Haystack to the new Resolwe's elastic app.

**Comment by mstajdohar** [comment]
What is the status of this?

**Comment by mstajdohar** [comment]
@tjanez Is this still relevant?

**Comment by tjanez** [comment]
This has been fixed in #216.
