### ISSUE TITLE
Display sample names in the Cuffnorm box plot (not relation IDs)

### ISSUE THREAD

**Issue by JenkoB** [genialis/resolwe-bio#266]
In cuffnorm one of the outputs is boxplot. There should be sample names instead of replicates numbers.

The example is on BCM server: https://bcm.genialis.com/rna-seq/bioinformatics/collection/p4936_ms2_rna/data/slug/cuffnorm-p4936_rna_ms2_2hr_r2-p4936_rna_ms2_8hr_r3-p4936_rna_ms2_8hr_r2-p4936_rna_ms2_8hr_r1-2?_b=15c8ff39-d90b-487f-a40c-12912ba5c838&_s=36d81108-56f8-4d3d-8f88-995631216903

[cuffnorm_exprs_boxplot (5).pdf](https://github.com/genialis/resolwe-bio/files/978591/cuffnorm_exprs_boxplot.5.pdf)

**Comment by mstajdohar** [comment]
cc @rafecooks

**Comment by jkokosar** [comment]
Labels in box plot are the same as user added labels in the inputs of the cuffnorm process. Since the labels start with numerical value, R adds "X" at the beginning of the string.

**Comment by jkokosar** [comment]
Ok, so those are not user provided sample labels, but relation ids derived from resdk utility functions: https://github.com/genialis/resolwe-bio-py/blob/master/resdk/analysis/expressions.py#L121

**Comment by mstajdohar** [comment]
@jvrakor discuss with @jkokosar and @dblenkus about the solution.
