### ISSUE TITLE
Remove obstolete Mongo escaping

### ISSUE THREAD

**Issue by kostko** [genialis/resolwe-bio#370]
There is some left-over escaping for MongoDB syntax from the times that Resolwe used MongoDB. It should be removed as it may cause problems.

Function in question, which is used in some places and should be removed:
https://github.com/genialis/resolwe-bio/blob/9518106c09be420a78f7298b328071d3299e8751/resolwe_bio/tools/utils.py#L11-L13

**Comment by mstajdohar** [comment]
@jkokosar We call `escape_mongokey` in tools' scripts.

**Comment by mzganec** [comment]
Fixed in [https://github.com/genialis/resolwe-bio/pull/371](https://github.com/genialis/resolwe-bio/pull/371).
