### ISSUE TITLE
Sample API resource is inconsistent with the rest of the API

### ISSUE THREAD

**Issue by kostko** [genialis/resolwe-bio#39]
It would be more consistent with the rest of the API if the `Sample` resource was accessible via `/api/sample` and `annotated` would be a filter query argument. So you would then do queries:
* `/api/sample?annotated=1` instead of `/api/sample/annotated`
* `/api/sample?annotated=0` instead of `/api/sample/unannotated`

This would make it more consistent for use in the GenJs frontend API.

**Comment by kostko** [comment]
Note that this also prevents sample queries from being reactive.

**Comment by dblenkus** [comment]
The plan is to support complex filtering on standard endpoints and than remove `sample` endpoint, as we will be able to get same results through filtering `collection` endpoint.

**Comment by kostko** [comment]
That would be even better.
