### ISSUE TITLE
Bug in Subread process (data:alignment:bam:subread)

### ISSUE THREAD

**Issue by lukaw3d** [genialis/resolwe-bio#448]
https://github.com/genialis/resolwe-bio/blob/f7a80b56fa730306213ce10bd8a31968a3c72fd6/resolwe_bio/processes/alignment/subread.yml#L167-L168

<br>
<br>

The second line should be
```
-p {{ PE_options.consensus_subreads }}
```

**Comment by JenkoB** [comment]
True.

**Comment by JenkoB** [comment]
PR to fix: https://github.com/genialis/resolwe-bio/pull/449

**Comment by lukaw3d** [comment]
@jkokosar I thought I'd look for unused inputs in all processes, and here are the potential issues I found:
* [x] alignment-subread doesnt use "PE_options.consensus_subreads"
* [ ] alignment-tophat2 doesnt use "PE_options.library_type"
* [ ] icount-demultiplex doesnt use "mismatches" and "minimum_length"
* [ ] bbduk-single doesnt use "trimming_par.minlength"
* [ ] bbduk-paired doesnt use "trimming_par.minlength"
* [ ] workflow-chip-seq doesnt use "annotation"

**Comment by lukaw3d** [comment]
If someone wants to add a pull-request validation (e.g. @tjanez || @dblenkus ) to find these, here's pseudocode of my javascript searcher:
```
get processes (last version per slug)
for each process:
    get a list of input field names (for fields inside groups use full path (e.g. "protocols.growth_protocol"))

    ignore fields named "advanced"

    str = (get process code string || stringify workflow json) + process.data_name
    if str doesn't contain one of the field names:
        print bad process
        unless one of ['test-disabled', 'test-hidden', 'test-all-fields-with-description', 'test-output', 'test-express']
```

**Comment by jkokosar** [comment]
@mzganec Please not the bbduk issues above. Please fix this in your future PR. Barbara will tackle the rest

**Comment by mstajdohar** [comment]
Did we fix this issues in processes? Did we write the test @lukaw3d suggested?

**Comment by JenkoB** [comment]
I have fixed following bugs:
alignment-subread doesnt use "PE_options.consensus_subreads"
alignment-tophat2 doesnt use "PE_options.library_type"
workflow-chip-seq doesnt use "annotation"

Process icount-demultiplex is not in use anywhere, so we have discussed with @jkokosar to remove it.

**Comment by mstajdohar** [comment]
Please remove `icount-demultiplex` as planned. What about `bbduk-single` and `bbduk-paired`?

**Comment by JenkoB** [comment]
ok. I don't know about bbduk. @mzganec do you still plan to improve bbduk process and also fix this to bugs?

**Comment by mzganec** [comment]
Yes.

**Comment by JenkoB** [comment]
@mstajdohar do we have any way how to remove ```icount-demultiplex``` process or any other process? This probably needs to be done manually at the time of redeploy or is other way?

**Comment by JureZmrzlikar** [comment]
I can add this into data migrations. And @jkokosar can remove it in his PR [genialis-bio#4](https://github.com/genialis/genialis-bio/pull/4).

**Comment by mstajdohar** [comment]
It needs to be done manually. Admins can probably delete the process by removing it with ReSDK. The problem is if this process was used to create data objects. If data objects exist, the system will not allow you to delete a process, since this data objects link to the process for details. We should discuss a solution with @dblenkus. Maybe we could introduce the ADD permission on the process which would mean you are allowed to run a process. Now the VIEW permissions allows you to run and see a process. If we supported ADD for running, we could use the VIEW permission just for displaying process' details in the data page.

**Comment by jkokosar** [comment]
@JureZmrzlikar As suggested, `icount-demultiplex` process is removed here: https://github.com/genialis/genialis-bio/pull/4/commits/c1d1e4431f1f48b76d8194a40ff9105570b3a2f2

**Comment by dblenkus** [comment]
One option is to include this into migrations and automatically delete all data objects created with that process. If you want to check which objects will be deleted you can do this with ReSKD:

    for p in res.process.filter(slug='icount-demultiplex'):
        print(res.data.filter(process=p.id))

But you cannot delete the process over the API as it doesn't support that. If this will be needed more often, it can be easily supported.

**Comment by JureZmrzlikar** [comment]
Removal of `icount-demultiplex` has already [been included in migrations](https://github.com/genialis/genialis-base/pull/361/files#diff-0323f8a06c43095cefc8ada1a2ffb966R181).

**Comment by mstajdohar** [comment]
@mzganec Did you fix bbduk? @dblenkus Did you remove icount-demultiplex?

**Comment by mzganec** [comment]
This is my next task.
