### ISSUE TITLE
Fix resolwebio/utils Docker image

### ISSUE THREAD

**Issue by tjanez** [genialis/resolwe-bio#509]
Currently, building this Docker images on Docker Hub fails with:

```
Downloading 'ncbi/sra-toolkit' version '2.8.2-1'...

Fetching 'https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/current/sratoolkit.current-ubuntu64.tar.gz'...

Verifying package...

[91mERROR: SHA256 digest mismatch.
```

Here is an [example build log](https://hub.docker.com/r/resolwebio/utils/builds/bf2aea8aaktdsyjdmrbnzbs/).

**Comment by mzganec** [comment]
Fix in https://github.com/genialis/resolwe-bio/pull/508.

**Comment by tjanez** [comment]
Great, thanks!
